### PR TITLE
upgraded to swaggerize-routes and new swagerize-express

### PR DESCRIPTION
**Pull request by tlivings**

### CODE REVIEW

**Comment by subeeshcbabu** [comment]
merge conflicts?

**Comment by kenjones-cisco** [comment]
@tlivings  Is there an ETA on this PR?

**Comment by tlivings** [comment]
@kenjones-cisco should be done today!

**Comment by aredridel** [comment]
Shiny! Looks straightforward!

**Comment by subeeshcbabu** [comment]
+1 looks good

**Pull request merged**
