### PR TITLE
Major version v3.0.0

### PR DESCRIPTION
**Pull request by subeeshcbabu**
-  https://github.com/krakenjs/generator-swaggerize/milestones/v3.0.0

Acceptance criterion for this Major version PR

- [x] Should generate an end to end working application for the chosen framework.
- [x] Should generate `handlers`, `data` and `tests` based on the swagger api `paths`
- [x] Should generate `security` authorize handlers based on the swagger api `securityDefinitions`
- [x] The `package.json` of the application should have all the user inputs (such as name, github name etc)
- [x] The application should provide `mock` data by default using the mock data generator
- [x] The application should have unit tests with `mock` requests and response validators

### CODE REVIEW

**Comment by maxmil7** [comment]
@subeeshcbabu new restify project seems to be failing during install with the following error:
npm ERR! peerinvalid The package restify@4.1.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer swaggerize-restify@2.0.10 wants restify@^3.0.3

**Comment by subeeshcbabu** [comment]
Thx @maxmil7 . Looks like `swaggerize-restify` latest version `2.0.10` supports only `restify@^3`. let me use that version as part of the generator

**Comment by grawk** [comment]
👍

**Comment by maxmil7** [comment]
👍

**Pull request merged**
