### PR TITLE
Add support for YAML Swagger files

### PR DESCRIPTION
**Pull request by mohsen1**

### CODE REVIEW

**Comment by mohsen1** [comment]
Tests are missing, please guide me to add tests.

**Comment by tlivings** [comment]
Does this support need to exist in `swaggerize-hapi` and `swaggerize-express` as well?

**Comment by mohsen1** [comment]
With Swagger 2.0, there is a lot of YAML Swagger specs out there. It would be a good to have feature for those libraries too.

**Comment by tlivings** [comment]
I agree. I am going to pull in your commit but I think it needs a little more work. For example, if we start with yaml then we should copy the yaml across to config directory. Consequently, support will need to be added to the other projects as well.

**Comment by tlivings** [comment]
Closing in favor of https://github.com/krakenjs/generator-swaggerize/pull/30. Your commits are available there.

**Comment by mohsen1** [comment]
:+1:

**Pull request closed without merging**
