### PR TITLE
swaggerize-restify support

### PR DESCRIPTION
**Pull request by bardzusny**
Hi,

I forked `swaggerize-express` and modified it to work with [restify](http://mcavage.me/node-restify/) - basically made what `swagger-node-restify` is to `swagger-node-express`. I would love to get it supported by this generator, and this PR provides just that - any suggestions/comments welcome.

### CODE REVIEW

**Comment by bardzusny** [comment]
I updated PR to use `swaggerize-restify` 2.x.x - with merged changes from `swaggerize-express` 4.x.x. The only backwards-incompatible feature I can see, that actually matters in provided with `generator-swaggerize` app templates, is specyfing API `host` by setting `app.swagger.api.host` property instead of using `app.setHost()` method.

**Comment by tlivings** [comment]
This is awesome! Will review and comment shortly, thanks.

I apologize that this has sat here so long. To be honest it totally went under my radar, otherwise I would have engaged a lot sooner.

**Comment by tlivings** [comment]
This looks pretty good to me. My only concern would be keeping things in sync with swaggerize-restify.

**Comment by bardzusny** [comment]
There are no ambitions above being a mere port of what is already there in `swaggerize-express`* - I wouldn't worry at all about feature-set "branching away" in any way.

I understand that's also a question of whether it will be properly maintained and kept up-to-date - all I can say here is that I'm pretty committed to that. Of course there's always possibility that it won't stay this way forever - if that ever happens, I see no obstacles on giving the project (and its `npm` package rights) away.

Let me know what you think.

* - to the degree allowed by `restify` itself - one recent example I can think of is its lack of support for mount paths.

**Comment by tlivings** [comment]
Sorry, I borked your merge due to some other merges.

**Comment by tlivings** [comment]
I wonder if there is something we can do to make `swaggerize-express` work with `restify` better so that there won't be a fork out there which is missing out on potentially important updates (like the recent security and vendor extensions update made in 4.0.0).

**Comment by bardzusny** [comment]
I fixed the mentioned merge conflict, everything should be OK now.

About making it possible to directly use `swaggerize-express` with `restify` - I'm really doubtful it would be viable, at all. Feel invited to look over my original commits to `swaggerize-restify` - I'm pretty sure making `swaggerize-express` take into account all the differences would lead to basically maintaining two sets of functions for much of its functionality - and tests as well, I believe.

I can't say I ever truly used or followed development of `express` that much - but I dare to say that, while originally incredibly similar in usage (from the REST use-case point of view), they diverged too much already for such approach to be sensible.

**Pull request merged**
